version: '3.8'
services:
  client:
    build:
      context: ./client
      target: runner
    volumes:
      - ./client:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"      